# Generated by Django 4.2.1 on 2023-05-28 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appareil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeAppareil', models.CharField(choices=[('O', 'Ordinateur'), ('PC', 'Ordinateur Portable'), ('IMP', 'Imprimante'), ('SCAN', 'SCANNER')], max_length=5)),
                ('marqueAppareil', models.CharField(max_length=20)),
                ('dateArrAppareil', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomClient', models.CharField(max_length=40)),
                ('prenomClient', models.CharField(max_length=50)),
                ('adresseClient', models.CharField(max_length=60)),
                ('telClient', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeIntervention', models.CharField(max_length=20)),
                ('problemeAppareil', models.CharField(max_length=100)),
                ('dateIntervention', models.DateField(auto_now=True)),
                ('appareil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.appareil', verbose_name='the related appareil')),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refPiece', models.CharField(max_length=20)),
                ('typePiece', models.CharField(max_length=20)),
                ('montantPiece', models.IntegerField(verbose_name=30)),
            ],
        ),
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numTechnicien', models.CharField(max_length=5)),
                ('nomTechnicien', models.CharField(max_length=40)),
                ('prenomTechnicien', models.CharField(max_length=50)),
                ('specialiteTechnicien', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Utiliser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtePiece', models.IntegerField(verbose_name=10)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.piece')),
                ('technicien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.technicien')),
            ],
        ),
        migrations.CreateModel(
            name='Reglement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeReglement', models.CharField(choices=[('ES', 'Espece'), ('BANK', 'Virement Bancaire'), ('Ch', 'Cheque'), ('TM', 'Transfert Monnaie')], max_length=5)),
                ('dateReglement', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.intervention')),
            ],
        ),
        migrations.AddField(
            model_name='intervention',
            name='technicien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.technicien', verbose_name='the related technicien'),
        ),
    ]
